SAHANAV_CLEANING_HOURS = 5
VIMARSHA_CLEANING_HOURS = 2
RAMESH_CLEANING_HOURS = 5
PRIYA_CLEANING_HOURS = 4
SAHANAV_KITCHEN_HOURS = 2
VIMARSHA_KITCHEN_HOURS = 2
RAMESH_KITCHEN_HOURS = 4
PRIYA_KITCHEN_HOURS = 3